# host_vars/pr001.yml
# Variables visible to pr001
---
#Firewall allow dns
rhbase_firawall_allow_services:
  - dns

#Bind
bind_allow_query:
  - '203.0.113.0/24'
  - '172.16.0.0/16'

bind_listen_ipv4:
  - any

bind_zones:
  - name: avlon.lan
    type: primary
    create_forward_zones: true
    create_reverse_zones: true
    primaries: 
     - 172.16.128.1
    name_servers:
      - pr001.avlon.lan.
      - pr002.avlon.lan.
    networks:
      - '203.0.113'
      - '172.16'
    hosts:
      - name: router
        ip: 
          - 203.0.113.254
          - 172.16.255.254
        aliases:
          - gw
      - name: pu001
        ip: 203.0.113.10
        aliases: 
          - www
      - name: pu002
        ip: 203.0.113.20
        aliases: mail
      - name: pr001
        ip: 172.16.128.1
        aliases:
          - ns1
      - name: pr002
        ip: 172.16.128.2
        aliases:
          - ns2
      - name: pr003
        ip: 172.16.128.3
        aliases:
          - dhcp
      - name: pr004
        ip: 172.16.128.4
        aliases:
          - directory
      - name: pr010
        ip: 172.16.128.10
        aliases:
          - inside
      - name: pr011
        ip: 172.16.128.11
        aliases:
          - files
    
mail_servers:
  - name: pu002
    preference: 10