# site.yml
---

- hosts: pu001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
  pre_tasks:
    - name: Copy web server private key
      copy:
        src: files/pu001.key
        dest: /etc/pki/tls/private/pu001.key
    - name: Copy web server certificate
      copy:
        src: files/pu001.crt
        dest: /etc/pki/tls/certs/pu001.crt

- hosts: pr001, pr002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

- hosts: pr011
  become: true
  roles: 
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd
  pre_tasks:
    - name: Add /sbin/nologin to /etc/shells. Allows local users to access ftp without shell access
      lineinfile:
        path: /etc/shells
        line: /sbin/nologin

- hosts: pr003
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp

- hosts: pr010
  become: true
  roles:
    - bertvv.rh-base
  tasks:
    - name: Installing Docker & Docker Compose
      yum: 
        name: 
          - docker
          - docker-compose
        state: latest
    - name: Starting & enabling Docker
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Copy docker-compose file to VM
      copy:
        src: files/docker-compose.yml
        dest: /home/vagrant/docker-compose.yml
    - name: Start containers with docker-compose
      shell:
        chdir: /home/vagrant/
        cmd: docker-compose up -d
  